label scene6:
    scene hallway2

    "Sure enough, Yumi was waiting for me."
    "I thought her time-out was supposed to relax her, but instead it just wound her up even tighter."

    pro "I must say, Sis, your evil energies are shining ever more radiantly today…"
    sis "Shut up. Are you ready to come clean about who this girl is?"
    pro "What girl? This is all a dream, right?"
    sis "Erghh! She {i}just{/i} walked by me! She's pillaging our kitchen right now!"
    sis "Where'd you even find her!? Is it some sleazy dating site for edgy little creeps like you?"
    pro "Hey now, that's going a little far! I'm of average height for someone my age!"
    sis "Is that's really the part you're taking issue with…?"
    pro "Besides, didn't I already introduce you two?"
    sis "Yeah, Beepy or whatever.."
    sis "She's not, like, {i}actually{/i} a demon of sloth, right? Did you pay her to play out your sick-minded roleplay or something?"
    pro "I-It's not a roleplay! She's actually a demon!"
    sis "Rrgh… I hate to admit it, but…"
    sis "...I might have to believe you."
    pro "...Really?"

    "This was weird. My sister had always been skeptical of my dark magic."
    "Usually she'd just dismiss it as some kind of dorky LARPing thing; she never understood before, so why start now?"

    sis "...I mean, I considered other explanations, but I really can't believe them either."
    sis "Like… she can't be your cosplayer girlfriend, for one."
    pro "W-What!? {b}Girlfriend?{/b}"
    sis "Yeah, you don't really have the charisma for that. Or the personality. Or, well, anything that a girl would want."
    pro "Th-Thanks for the vote of confidence, sis."
    sis "Heheh. I call it like it is~"

    "Stupid Yumi. Always teasing me like this."
    "The worst part is that she possesses a demon lord’s blood inside of her. By sorceror law, I can't bring harm to her."
    "She is a lucky, utterly oblivious sort. I curse that fact frequently."
    "...She also has a good foot on me, so if I tried… she could probably throw me pretty far."

    sis "Yeah, there's no way you could land a girl as cute as her."
    pro "'C-Cute?' She's an extremely powerful demon, you realize."
    #sister blush for this line
    sis "D-Did I say cute? I mean, ah… um…"
    sis "J-Joking aside… this demon business is hard to swallow, Makoto."
    sis "I guess you're going to tell me you summoned her or some shit."
    pro "Actually, yeah, that's exactly it. The altar was in the garage, you saw it."
    sis "Oi… Sticking to that story, huh…"
    sis "I can't believe you. I thought Mom and Dad explicitly told you that bringing evil beings and spirits into our house was off-limits!"
    pro "What makes you think Beepy's evil, though?"
    sis "...Excuse me? You keep calling her a demon, right?"
    pro "Well, yeah, she is, but that doesn't make her evil by default."
    pro "You're coming off as a little judgmental there, Yumi."
    sis "You brat…!"

    "Yumi grimaced visibly, and I could immediately tell I had the upper hand in this battle of ours."

    sis "Alright, let's just assume she's {i}actually{/i} a demon, I guess. I don't believe it, but for the sake of argument..."
    pro "Devil's advocate, in a nutshell."
    sis "Does everything have to be evil Satanic crap with you!? Let me finish!"
    pro "Uhh, that's not really… Wh-Whatever, okay, so... what?"
    sis "She's just visiting, right? She should probably go back to her place soon; it's getting dark and I need to cook."
    pro "Well, uh, I don't think that would work."
    pro "She's technically my familiar, so she would probably have to stay with me."
    sis "...What? But there's nowhere she can stay! Mom and Dad would kill me twice over if they knew I let her sleep here!"
    pro "She can't exactly sleep out on the streets, though…"

    #enter beepy stage left

    bp "I mean, I guess I could? Wouldn't be really comfortable, though. A bed would be so much nicer."
    pro "Wh-- Beepy!?"
    sis "Wh-Wh-Where did you come from!?"
    bp "Heard my name. Juuust eavesdropping."
    bp "But yeah, Makoto's right. I could use a place to stay."
    bp "I mean, if that's not a problem. I assume you guys aren't, like, crazy fundamentalist Christians, right?"
    pro  "Well, we celebrate Christmas - but otherwise, not… really?"
    sis "And if you wanna talk crazy, I mean… you've already met my brother, right?"
    bp "Oh, yeah, don't know how you put up with him. He's a huge dork."
    sis "Right!? Finally, somebody says something about it!" 
    sis "You know he never washes that cape, right?"
    bp "Ohhh, I can tell…"
    pro "I’m right here!" 
    sis "We know."
    bp "We know."

    "They shared a cheap laugh at my expense - likely the first of many"
    "Besides, capes ventilate themselves anyway, it's not a big deal!"

    bp "Say, we should probably talk about this over food. You guys wanna order a pizza?"
    sis "Well, it's probably too late to cook something…"
    sis "But Makoto has to foot the bill."
    pro "Wha-- Why me!?"
    sis "Well, if your story is that you summoned her and stuff, you should probably take some more responsibility."
    bp "Heh! She's got you there, Mister Demon Lord."
    pro "I-I have a title, you know…"
    bp "C'mooon, I'm starving!"
    pro "Ugh… This is going to blow a huge hole in my wallet."
    sis "Heh! This isn't actually so bad…"

    scene black
    "The three of us moved into the living room..."

    bp "I want a large Hawaiian pizza! Oh, and {i}extra{/i} pineapple on top!"
    sis "P-Pineapple on pizza? Wow, you really are a demon, aren't you…?"
    pro "Is that really the part you're taking issue with, Yumi!?"
    "After some deliberation, we placed the order and bided our time..."
    "..."
    "... …"
    "... … …"
    jump scene7
